[build]
  command = ""
  publish = "."

[[redirects]]
  from = "https://www.alphalumina.com/*"
  to = "https://alphalumina.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/lander"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
